services:
  postgres:
    image: 'ankane/pgvector:v0.5.1'
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "pg_isready -U postgres -d vectordb" ]
      interval: 2s
      timeout: 20s
      retries: 10
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.com}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}'
    volumes:
      - '/servers.json:/pgadmin4/servers.json'
    ports:
      - '${PGADMIN_PORT:-5050}:80'




